### ISSUE TITLE
Improvement: image should take name instead of UUID

### ISSUE THREAD

**Issue by StefanScherer** [kaorimatz/vagrant-scaleway#1]
First thank you for beginning this Vagrant plugin. It's my first time to `vagrant up` a baremetal machine.

I tried to use `scaleway.image = 'Ubuntu_Xenial'` but the plugin wants the UUID. With the UUID I got from `scw images --no-trunc` the plugin still didn't find the image. 

So I just tried a `Vagrantfile` without the image configuration.

It would be easier to use the image name.

**Comment by kaorimatz** [comment]
Hi @StefanScherer, thank you for providing feedback and sorry for the inconvenience. This plugin doesn't accept an image name for specifying the image. I'm willing to consider adding that feature. For now, you can find the list of available images from the output of `vagrant scaleway images`. 

```
$ vagrant scaleway images | grep -e 'Image ID' -e 'Ubuntu Xenial'
Image ID                              Created At                 Arch    Default Bootscript                   Image Name
047f1372-3923-471f-82ca-5ff69dbaf0f7  2016-04-22 12:45:25 +0000  x86_64  x86_64 4.5.1 std #1 (stable/latest)  Ubuntu Xenial (16.04 latest)
e84d5466-bc36-453f-9d9a-de81b09bc199  2016-04-22 13:06:31 +0000  arm     armv7l 4.3.5 std #1 (latest)         Ubuntu Xenial (16.04 latest)
4d6e9a43-5f6b-4dde-8010-abadf460e7f2  2016-04-25 16:03:50 +0000  arm     armv7l 4.5.2 std #1 (latest)         Ubuntu Xenial (16.04 latest)
75c28f52-6c64-40fc-bb31-f53ca9d02de9  2016-05-20 09:35:48 +0000  x86_64  x86_64 4.5.7 std #3 (latest/stable)  Ubuntu Xenial (16.04 latest)
a86150a9-6d0f-4692-bd64-0b4a8662e089  2016-04-25 15:32:23 +0000  x86_64  x86_64 4.5.2 std #1 (latest/stable)  Ubuntu Xenial (16.04 latest)
eeb73cbf-78a9-4481-9e38-9aaadaf8e0c9  2016-05-20 09:00:08 +0000  arm     armv7l 4.5.7 std #4 (latest)         Ubuntu Xenial (16.04 latest)
```

**Comment by StefanScherer** [comment]
Thanks. Didn't know `vagrant scaleway` command. This helps fetching the image ID. So it would be difficult to use the image name as there are multiple images available.

**Comment by kaorimatz** [comment]
Yes, we need to choose the one from the matching images, such as the most recently created one.
