### ISSUE TITLE
Specifying volume size(s)

### ISSUE THREAD

**Issue by hrbrmstr** [kaorimatz/vagrant-scaleway#2]
Very basic config with a VC1M server resulted in:

>The sum of volumes sizes of VC1M instances must be between 51GB and 100GB

I don't see a way to specify that in the config. I looked through the ruby plugin source and didn't see it specifying this value anywhere. Not sure if it's an issue on my end or with the plugin (just started using Scaleway).

NOTE: It looks like `C1` images work fine w/o specifying volume sizes.

**Comment by kaorimatz** [comment]
Hi @hrbrmstr, thank you for taking time for reporting this.
The size of the root volume is fixed to 50GB in Scaleway, so it seems that VC1M and VC1L require additional volumes to be attached at creation time, but this plugin doesn't support this yet. I'll put it on my task list.

**Comment by tkhduracell** [comment]
@kaorimatz Would be cool to implement this!

**Comment by kaorimatz** [comment]
Now we can attach additional volumes to the server in v0.4.0. Thanks for reporting!

```
Vagrant.configure('2') do |config|
  config.vm.provider :scaleway do |scaleway, override|
    scaleway.commercial_type = 'VC1M'
    scaleway.volumes = [
      { size: 50_000_000_000 }
    ]
    override.ssh.private_key_path = '~/.ssh/id_rsa'
  end
end
```
