### ISSUE TITLE
undefined method and Datacenter location

### ISSUE THREAD

**Issue by skarfr** [kaorimatz/vagrant-scaleway#5]
Hi,

When I try to run `vagrant scaleway images`, i get the error:
`/.vagrant.d/gems/2.2.5/gems/vagrant-scaleway-0.3.0/lib/vagrant-scaleway/action/list_images.rb:15:in 'block in call': undefined method 'title' for nil:NilClass (NoMethodError)`

Also, i noticed that Scaleway propose 2 datacenter locations (France & Netherlands). Is there a parameter to handle this property ?

Thanks for the plugin and for your help,

p.

**Comment by skarfr** [comment]
I missed the `region` parameter. This is the one handling the datacenter location.

**Comment by kaorimatz** [comment]
@skarfr Thank you for letting me know! I have just fixed it and released v0.3.1. I'm closing this issue, if you still have problems feel free to reopen it.
